// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAp5dhfLbB-FgDvGhQp7CyP3PcAyjWnxhc',
    appId: '1:360483034840:web:6afa3b001ff6b8642c29ad',
    messagingSenderId: '360483034840',
    projectId: 'exercise-75165',
    authDomain: 'exercise-75165.firebaseapp.com',
    storageBucket: 'exercise-75165.appspot.com',
    measurementId: 'G-B1MGM27KVL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB07aiR3MStS0VnLxzxIwN7rtaJS-42Y7c',
    appId: '1:360483034840:android:5e3c4648f2baec032c29ad',
    messagingSenderId: '360483034840',
    projectId: 'exercise-75165',
    storageBucket: 'exercise-75165.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCMcMqbO6SvVD9jTFA9ywgzAFXt-9refSI',
    appId: '1:360483034840:ios:93b9ef445993e3e92c29ad',
    messagingSenderId: '360483034840',
    projectId: 'exercise-75165',
    storageBucket: 'exercise-75165.appspot.com',
    iosBundleId: 'com.example.project',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCMcMqbO6SvVD9jTFA9ywgzAFXt-9refSI',
    appId: '1:360483034840:ios:93b9ef445993e3e92c29ad',
    messagingSenderId: '360483034840',
    projectId: 'exercise-75165',
    storageBucket: 'exercise-75165.appspot.com',
    iosBundleId: 'com.example.project',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAp5dhfLbB-FgDvGhQp7CyP3PcAyjWnxhc',
    appId: '1:360483034840:web:bf62d1351220b9352c29ad',
    messagingSenderId: '360483034840',
    projectId: 'exercise-75165',
    authDomain: 'exercise-75165.firebaseapp.com',
    storageBucket: 'exercise-75165.appspot.com',
    measurementId: 'G-TTHNNVYZ5M',
  );
}
